const rooms = [
  {
    id: '1',
    title: 'Minecraft',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 6,
    max_players: 10,
  },
  {
    id: '2',
    title: 'Guitar Hero',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 7,
    max_players: 10,
  },
  {
    id: '3',
    title: 'Gartic Phone',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 10,
    max_players: 10,
  },
  {
    id: '4',
    title: 'Gartic',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 1,
    max_players: 10,
  },
  {
    id: '5',
    title: 'Stardew Valley',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 3,
    max_players: 10,
  },
  {
    id: '6',
    title: 'FIFA',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 2,
    max_players: 10,
  },
  {
    id: '7',
    title: 'Payday 2',
    plataform: 'Discord',
    date: '06/07/2023   |   19h',
    players: 3,
    max_players: 10,
  },
];

export default rooms;